image:
  file: .gitpod.Dockerfile

tasks:
  - init: 'echo "TODO: Replace with init/build command"'
    command: 'dotnet build WebApplication1.csproj'  
  - command: 'dotnet bin/debug/netcoreapp3.1/WebApplication1.dll'