image:
  file: .gitpod.Dockerfile

tasks:
  - init: 'echo "TODO: Replace with init/build command"'
    command: dotnet build WebApplication1.csproj  && dotnet bin/Debug/netcoreapp3.1/WebApplication1.dll

ports:
  - port: 5000
    onOpen: open-preview

